### ISSUE TITLE
Self-contained data

### ISSUE THREAD

**Issue by KaiZhuPhD** [zhulabgroup/song-2023-landsc-ecol#1]
Make data files self-contained in this repo, independent of the server.

https://github.com/zhulabgroup/song-2023-landsc-ecol/blob/fbe261c9cdadfbfd76d908af3ca612779b0f624f/empirical/bird/code.R#L66

**Comment by yiluansong** [comment]
I have removed the code for extracting climate data. The extracted data are in a file in this repo so it should be okay.
