### ISSUE TITLE
R session aborted in bird case study 

### ISSUE THREAD

**Issue by KaiZhuPhD** [zhulabgroup/song-2023-landsc-ecol#4]
The following code causes the R session to be terminated.

https://github.com/zhulabgroup/song-2023-landsc-ecol/blob/2b5e34f9999bd619f9d8623cd38b2469db1f91a9/empirical/bird/code.R#L60-L69

**Comment by yiluansong** [comment]
This is because of memory usage most likely. When I set memory 5 GB, my R session does terminate; when I set it to 10 GB, the code can run.
